version: "3.3"

volumes:
  grafana-storage:
    driver: local
  kubotdb-storage:
    driver: local

services:
  postgres:
    image: postgres:12
    container_name: kubot-db
    restart: on-failure:10
    ports:
    - 5433:5432
    environment:
      - POSTGRES_USER=kubot
      - POSTGRES_PASSWORD=kubot
      - POSTGRES_DB=kubot
    volumes:
    - kubotdb-storage:/var/lib/postgresql/data
  kubot:
    image: ${KUBOT_IMAGE}:${KUBOT_VERSION}
    container_name: kubot
    restart: on-failure:10
    depends_on:
      - postgres
    volumes:
    - ./config/config:/app/config/config
  grafana:
    image: grafana/grafana
    container_name: kubot-gui
    restart: on-failure:10
    depends_on:
      - postgres
    environment:
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/etc/grafana/certs/grafana.crt
      - GF_SERVER_CERT_KEY=/etc/grafana/certs/grafana.key
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./certs:/etc/grafana/certs:ro
      - ./provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000
