{
 "title": "Overview",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Profit USDT",
   "type": "gauge",
   "description": "This panel includes all your realized and upcoming profit.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select\n    time,\n    coalesce((select coalesce((select (c.assets->0->>'accruedInterest')::numeric from lendingassets as c where c.time <= now() - interval '1 day' and c.time >= now () - interval '2 day' order by c.time desc limit 1), 0) - (b.assets->0->>'accruedInterest')::numeric from lendingassets as b where b.time <= now() - interval '2 day' and b.time >= now () - interval '3 day' order by b.time desc limit 1), 0) as dailyInterest,\n    (assets->0->>'accruedInterest')::numeric as accruedinterest,\n    (assets->0->>'realizedProfit')::numeric as realizedprofit,\n    coalesce((assets->0->>'accruedInterest')::numeric, 0) + (assets->0->>'realizedProfit')::numeric as totalprofit\nfrom lendingassets\norder by 1;"
    }
   ]
  },
  {
   "title": "Active Lending - Total Amount USDT",
   "type": "graph",
   "description": "Active Lending Total Amount USDT",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Total Amount USDT" }
   ],
   "targets": [
    {
     "rawSql": "select \ntime, sum((active_order->>'size')::numeric - (active_order->>'repaid')::numeric) as totalSize\nfrom activelendorder\ncross join json_array_elements(items) as active_order\nwhere currency = 'USDT'\ngroup by time\norder by 1;\n"
    }
   ]
  },
  {
   "title": "Active Lending - Accrued Interest USDT",
   "type": "graph",
   "description": "Showing the accrued interest in USDT",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Accrued Interest USDT" }
   ],
   "targets": [
    {
     "rawSql": "select \ntime, sum((active_order->>'accruedInterest')::numeric) as accrued_interest\nfrom activelendorder\ncross join json_array_elements(items) as active_order\nwhere currency = 'USDT'\ngroup by time\norder by 1;"
    }
   ]
  },
  {
   "title": "Active Lending - Avg Daily Interest Rate USDT",
   "type": "graph",
   "description": "Active Lending - Average Daily Interest Rates USDT",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Avg Daily Int Rate" }
   ],
   "targets": [
    {
     "rawSql": "select \ntime, trunc(avg((active_order->>'dailyIntRate')::numeric * 100), 3) as daily_intRate\nfrom activelendorder \ncross join json_array_elements(items) as active_order \nwhere currency = 'USDT' \ngroup by time \norder by 1;\n"
    }
   ]
  },
  {
   "title": "Total Amount Funding Market USDT",
   "type": "graph",
   "description": "Total Amount Funding Market USDT",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Total Amount USDT" }
   ],
   "targets": [
    {
     "rawSql": "select time, sum((size->>'size')::integer) as totalAmount\nfrom fundingmarket \ncross join json_array_elements(market) as size \ngroup by time \norder by 1\n"
    }
   ]
  },
  {
   "title": "Funding Market USDT",
   "type": "graph",
   "description": "Show daily interest rate % of USDT funding market.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Daily Interest Rate %" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time as time,\n  trunc(((market->0->>'dailyIntRate')::numeric * 100), 3) as dailyIntRate\nFROM fundingmarket\nWHERE currency = 'USDT'\nORDER BY 1"
    }
   ]
  }
 ]
}